package com.uni.communication.dto;

public enum MessageType {
    JOIN_LOBBY,
    JOINED_LOBBY,
    NEW_PLAYER_JOINED,
    CHEATING_TILT_RIGHT,
    CHEATING_TILT_LEFT,
    PLAYER_LEFT_LOBBY,
    LEAVE_LOBBY,
    REQUEST_CARDS,
    SEND_CARDS,
    START_GAME,
    UPDATE_BOARD,
    WORMHOLE_MOVE,
    PUNISHMENT_MESSAGE

}
